## IMPORTING THE LIB

In [40]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image
plt.style.use('classic')
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

### Importing the dataset

In [41]:
sales_df = pd.read_csv('nyc-rolling-sales.csv')

In [42]:
sales_df.head()

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00

### Coverting the SALE PRICE to Numeric Value

In [43]:
sales_df['SALE PRICE'] = pd.to_numeric(sales_df['SALE PRICE'], errors='coerce')
sales_df.head()

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000.0,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,NaN,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,NaN,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272.0,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000.0,2016-11-17 00:00:00

### Drop the Null value rows.

In [44]:
new_df = sales_df[sales_df['SALE PRICE'].notnull()]
len(sales_df)

84548

In [45]:
new_df.shape

(69987, 22)

In [46]:
sales_df.isnull().sum()

Unnamed: 0                            0
BOROUGH                               0
NEIGHBORHOOD                          0
BUILDING CLASS CATEGORY               0
TAX CLASS AT PRESENT                  0
BLOCK                                 0
LOT                                   0
EASE-MENT                             0
BUILDING CLASS AT PRESENT             0
ADDRESS                               0
APARTMENT NUMBER                      0
ZIP CODE                              0
RESIDENTIAL UNITS                     0
COMMERCIAL UNITS                      0
TOTAL UNITS                           0
LAND SQUARE FEET                      0
GROSS SQUARE FEET                     0
YEAR BUILT                            0
TAX CLASS AT TIME OF SALE             0
BUILDING CLASS AT TIME OF SALE        0
SALE PRICE                        14561
SALE DATE                             0
dtype: int64

In [47]:
len(sales_df["NEIGHBORHOOD"].unique())

254

In [48]:
y = new_df["SALE PRICE"]

In [49]:
X = new_df.drop(columns=["SALE PRICE"])

In [50]:
X.head()

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,10009,5,0,5,1633,6440,1900,2,C2,2017-07-19 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10009,10,0,10,2272,6794,1913,2,C4,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,10009,6,0,6,2369,4615,1900,2,C2,2016-11-17 00:00:00
6,10,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,,C4,210 AVENUE B,...,10009,8,0,8,1750,4226,1920,2,C4,2016-09-23 00:00:00
9,13,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,,D9,629 EAST 5TH STREET,...,10009,24,0,24,4489,18523,1920,2,D9,2016-11-07 00:00:00

### Droping the Not Nesscary

In [51]:
X = X.drop(columns=["ADDRESS"])

In [52]:
X = X.drop(columns=["SALE DATE"])

In [53]:
X = X.drop(columns=["EASE-MENT"])

In [54]:
X = X.drop(columns=["APARTMENT NUMBER"])

In [55]:
X = X.drop(columns=["Unnamed: 0"])

In [56]:
X.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,C2,10009,5,0,5,1633,6440,1900,2,C2
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,C4,10009,10,0,10,2272,6794,1913,2,C4
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,C2,10009,6,0,6,2369,4615,1900,2,C2
6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,C4,10009,8,0,8,1750,4226,1920,2,C4
9,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,D9,10009,24,0,24,4489,18523,1920,2,D9

### Converting the non int features to int.

In [57]:
X["LAND SQUARE FEET"] = X["LAND SQUARE FEET"].replace(' -  ', 0)

In [58]:
X["LAND SQUARE FEET"] = pd.to_numeric(X["LAND SQUARE FEET"])

In [59]:
X["GROSS SQUARE FEET"] = X["GROSS SQUARE FEET"].replace(' -  ', 0)
X["GROSS SQUARE FEET"] = pd.to_numeric(X["GROSS SQUARE FEET"])
X.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,C2,10009,5,0,5,1633,6440,1900,2,C2
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,C4,10009,10,0,10,2272,6794,1913,2,C4
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,C2,10009,6,0,6,2369,4615,1900,2,C2
6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,C4,10009,8,0,8,1750,4226,1920,2,C4
9,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,D9,10009,24,0,24,4489,18523,1920,2,D9

### Scaling the numeric

In [60]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
numerical = ['BLOCK', 'LOT', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',"LAND SQUARE FEET",'GROSS SQUARE FEET', 'YEAR BUILT']

scaled_X = X
scaled_X[numerical] = scaler.fit_transform(X[numerical])

scaled_X.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,0.023961,0.000549,C2,10009,0.002711,0.0,0.002211,0.000384,0.001717,0.941993,2,C2
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,0.024574,0.002197,C4,10009,0.005423,0.0,0.004423,0.000534,0.001811,0.948438,2,C4
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,0.024697,0.005931,C2,10009,0.003254,0.0,0.002654,0.000557,0.001230,0.941993,2,C2
6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,0.024819,0.003405,C4,10009,0.004338,0.0,0.003538,0.000412,0.001127,0.951909,2,C4
9,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,0.023655,0.016694,D9,10009,0.013015,0.0,0.010615,0.001056,0.004939,0.951909,2,D9

### One hot Encoding ofthe Non Numeric Data

In [61]:
features_final = pd.get_dummies(scaled_X)

In [62]:
zip_feature = pd.get_dummies(features_final['ZIP CODE'])

In [63]:
features_final.shape

(69987, 645)

In [64]:
final = pd.concat([features_final,zip_feature], axis=1)

In [65]:
borough_feature = pd.get_dummies(features_final['BOROUGH'])

In [66]:
borough_feature.shape

(69987, 5)

In [67]:
final = pd.concat([final,borough_feature], axis=1)
final = final.drop(columns=["BOROUGH"])
final = final.drop(columns=["ZIP CODE"])
final.rename(columns = {1:'BOROUGH_1'},inplace=True)
final.rename(columns = {2:'BOROUGH_2'},inplace=True)
final.rename(columns = {3:'BOROUGH_3'},inplace=True)
final.rename(columns = {4:'BOROUGH_4'},inplace=True)
final.rename(columns = {5:'BOROUGH_5'},inplace=True)

In [68]:
final.head()

,BLOCK,LOT,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,NEIGHBORHOOD_AIRPORT LA GUARDIA,...,11436,11691,11692,11693,11694,BOROUGH_1,BOROUGH_2,BOROUGH_3,BOROUGH_4,BOROUGH_5
0,0.023961,0.000549,0.002711,0.0,0.002211,0.000384,0.001717,0.941993,2,0,...,0,0,0,0,0,1,0,0,0,0
3,0.024574,0.002197,0.005423,0.0,0.004423,0.000534,0.001811,0.948438,2,0,...,0,0,0,0,0,1,0,0,0,0
4,0.024697,0.005931,0.003254,0.0,0.002654,0.000557,0.001230,0.941993,2,0,...,0,0,0,0,0,1,0,0,0,0
6,0.024819,0.003405,0.004338,0.0,0.003538,0.000412,0.001127,0.951909,2,0,...,0,0,0,0,0,1,0,0,0,0
9,0.023655,0.016694,0.013015,0.0,0.010615,0.001056,0.004939,0.951909,2,0,...,0,0,0,0,0,1,0,0,0,0

In [69]:
final.shape

(69987, 832)

### Train Test Split

In [77]:
from sklearn.cross_validation import train_test_split

# Split the 'features' and 'income' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(final, 
                                                    y, 
                                                    test_size = 0.2, 
                                                    random_state = 0)

In [78]:
len(X_test)

13998

In [79]:
len(X_train)

55989

In [80]:
len(y_test)

13998

In [81]:
len(y_train)

55989

In [82]:
y_train = scaler.fit_transform(y_train)

In [83]:
y_test = scaler.fit_transform(y_test)

In [113]:
X_train

,BLOCK,LOT,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,NEIGHBORHOOD_AIRPORT LA GUARDIA,...,11436,11691,11692,11693,11694,BOROUGH_1,BOROUGH_2,BOROUGH_3,BOROUGH_4,BOROUGH_5
42966,0.096335,0.000220,0.001085,0.000000,0.000885,0.000365,0.000435,0.951909,1,0,...,0,0,0,0,0,0,0,1,0,0
56368,0.329146,0.002526,0.000542,0.000000,0.000442,0.000847,0.000288,0.966782,1,0,...,0,0,0,0,0,0,0,0,1,0
6973,0.021571,0.111807,0.000542,0.000000,0.000442,0.000000,0.000000,0.994051,2,0,...,0,0,0,0,0,1,0,0,0,0
45128,0.062998,0.001098,0.001085,0.000000,0.000885,0.000247,0.000622,0.941993,1,0,...,0,0,0,0,0,0,0,1,0,0
4917,0.117233,0.015706,0.002169,0.000000,0.001769,0.000392,0.000666,0.946951,2,0,...,0,0,0,0,0,1,0,0,0,0
28372,0.387119,0.003954,0.017354,0.000885,0.015038,0.002822,0.007466,0.953892,2,0,...,0,0,0,0,0,0,0,1,0,0
25653,0.361809,0.001098,0.000542,0.000000,0.000442,0.000353,0.000543,0.954388,1,0,...,0,0,0,0,0,0,0,1,0,0
44847,0.059137,0.113234,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,0,0,1,0,0
38087,0.292499,0.000329,0.001085,0.000000,0.000885,0.000470,0.000678,0.969261,1,0,...,0,0,0,0,0,0,0,1,0,0
16155,0.071700,0.383965,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,1,0,0,0,0
18873,0.204805,0.018122,0.001085,0.000000,0.000885,0.000531,0.000738,0.946951,1,0,...,0,0,0,0,0,0,1,0,0,0
43914,0.440066,0.002746,0.001085,0.000000,0.000885,0.000486,0.000608,0.971740,1,0,...,0,0,0,0,0,0,0,1,0,0
30235,0.530947,0.066227,0.000000,0.000000,0.000000,0.000423,0.000000,0.000000,1,0,...,0,0,0,0,0,0,0,1,0,0
39560,0.129305,0.124876,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,0,0,1,0,0
50909,0.368734,0.005821,0.000542,0.000000,0.000442,0.001866,0.000570,0.961824,1,0,...,0,0,0,0,0,0,0,0,1,0
54628,0.096580,0.001757,0.000542,0.000000,0.000442,0.000494,0.000543,0.951909,1,0,...,0,0,0,0,0,0,0,0,1,0
7980,0.083344,0.001208,0.000000,0.000000,0.000000,0.000000,0.000000,0.957362,2,0,...,0,0,0,0,0,1,0,0,0,0
15832,0.070474,0.148600,0.000542,0.000000,0.000442,0.000000,0.000000,0.995042,2,0,...,0,0,0,0,0,1,0,0,0,0
58170,0.309045,0.158375,0.000542,0.000000,0.000442,0.000000,0.000000,0.971740,2,0,...,0,0,0,0,0,0,0,0,1,0
47473,0.056257,0.121142,0.000542,0.000000,0.000442,0.000000,0.000000,0.954883,2,0,...,0,0,0,0,0,0,0,1,0,0
34556,0.079360,0.006919,0.000000,0.000000,0.000000,0.000000,0.000000,0.955875,2,0,...,0,0,0,0,0,0,0,1,0,0
71547,0.834722,0.000000,0.001085,0.000000,0.000885,0.001462,0.000686,0.954388,1,0,...,0,0,0,0,0,0,0,0,1,0
27016,0.099277,0.008018,0.001627,0.000000,0.001327,0.000470,0.000880,0.941497,1,0,...,0,0,0,0,0,0,0,1,0,0
55220,0.080218,0.133224,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,0,0,0,1,0
10983,0.005454,0.133443,0.000542,0.000000,0.000442,0.000000,0.000000,0.999504,2,0,...,0,0,0,0,0,1,0,0,0,0
52923,0.784410,0.005272,0.000542,0.000000,0.000442,0.000941,0.000353,0.964303,1,0,...,0,0,0,0,0,0,0,0,1,0
44711,0.065388,0.006590,0.000000,0.000000,0.000000,0.000000,0.000000,0.951909,2,0,...,0,0,0,0,0,0,0,1,0,0
31427,0.199228,0.004393,0.001085,0.000000,0.000885,0.000441,0.000432,0.942489,1,0,...,0,0,0,0,0,0,0,1,0,0
29973,0.342260,0.121362,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,0,0,1,0,0
50348,0.034073,0.000220,0.000000,0.000000,0.000000,0.000000,0.000000,0.966782,2,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14749,0.095048,0.148710,0.000542,0.000000,0.000442,0.000000,0.000000,0.992563,2,0,...,0,0,0,0,0,1,0,0,0,0
56078,0.294092,0.000549,0.000542,0.000000,0.000442,0.000705,0.000363,0.966782,1,0,...,0,0,0,0,0,0,0,0,1,0
45371,0.071639,0.003954,0.000000,0.000000,0.000000,0.000000,0.000000,0.949430,2,0,...,0,0,0,0,0,0,0,1,0,0
59750,0.403603,0.000549,0.000000,0.000000,0.000000,0.000000,0.000000,0.960337,2,0,...,0,0,0,0,0,0,0,0,1,0
82794,0.208972,0.004613,0.000542,0.000000,0.000442,0.000811,0.000800,0.994051,1,0,...,0,0,0,0,0,0,0,0,0,1
56008,0.540385,0.003515,0.001085,0.000000,0.000885,0.000941,0.000674,0.966782,1,0,...,0,0,0,0,0,0,0,0,1,0
960,0.048903,0.002636,0.000000,0.000442,0.000442,0.002903,0.005648,0.951909,4,0,...,0,0,0,0,0,1,0,0,0,0
35788,0.125506,0.110599,0.000542,0.000000,0.000442,0.000000,0.000000,0.954883,2,0,...,0,0,0,0,0,0,0,1,0,0
28542,0.511276,0.016584,0.001085,0.000000,0.000885,0.000674,0.000366,0.984631,1,0,...,0,0,0,0,0,0,0,1,0,0
53113,0.242064,0.006919,0.001085,0.000000,0.000885,0.000941,0.000672,0.995042,1,0,...,0,0,0,0,0,0,0,0,1,0
3078,0.053315,0.005711,0.000000,0.000000,0.000000,0.000000,0.000000,0.941993,2,0,...,0,0,0,0,0,1,0,0,0,0
2319,0.001471,0.168040,0.000542,0.000000,0.000442,0.000000,0.000000,0.994051,2,0,...,0,0,0,0,0,1,0,0,0,0
10116,0.055644,0.004833,0.000000,0.000000,0.000000,0.000000,0.000000,0.983639,2,0,...,0,0,0,0,0,1,0,0,0,0
41486,0.418127,0.008018,0.001627,0.000000,0.001327,0.000470,0.001312,0.993059,1,0,...,0,0,0,0,0,0,0,1,0,0
81315,0.150080,0.226249,0.000542,0.000000,0.000442,0.000000,0.000000,0.981160,2,0,...,0,0,0,0,0,0,0,0,0,1
42671,0.528190,0.000220,0.000542,0.000000,0.000442,0.000882,0.000592,0.974219,1,0,...,0,0,0,0,0,0,0,1,0,0
8943,0.061834,0.006590,0.000000,0.000000,0.000000,0.000000,0.000000,0.946455,2,0,...,0,0,0,0,0,1,0,0,0,0
22850,0.350840,0.073806,0.000000,0.000000,0.000000,0.000000,0.000000,0.973723,2,0,...,0,0,0,0,0,0,1,0,0,0
36097,0.388405,0.005162,0.001085,0.000000,0.000885,0.000423,0.000547,0.959346,1,0,...,0,0,0,0,0,0,0,1,0,0
20956,0.150815,0.003515,0.000000,0.000000,0.000000,0.000000,0.000000,0.955875,2,0,...,0,0,0,0,0,0,1,0,0,0
59885,0.410406,0.004283,0.000000,0.000000,0.000000,0.000000,0.000000,0.967774,2,0,...,0,0,0,0,0,0,0,0,1,0
43379,0.398517,0.002856,0.001085,0.000000,0.000885,0.000373,0.000610,0.954388,1,0,...,0,0,0,0,0,0,0,1,0,0
54109,0.500429,0.014278,0.000542,0.000000,0.000442,0.002291,0.000424,0.971740,1,0,...,0,0,0,0,0,0,0,0,1,0
63146,0.872595,0.147831,0.000542,0.000000,0.000442,0.000847,0.000254,0.951909,1,0,...,0,0,0,0,0,0,0,0,1,0
45860,0.452139,0.006041,0.000542,0.000000,0.000442,0.000470,0.000196,0.951909,1,0,...,0,0,0,0,0,0,0,1,0,0
25110,0.285513,0.000988,0.001627,0.000000,0.001327,0.000559,0.000358,0.941497,1,0,...,0,0,0,0,0,0,1,0,0,0
50084,0.044184,0.002636,0.001627,0.000000,0.001327,0.000527,0.000710,0.956867,1,0,...,0,0,0,0,0,0,0,0,1,0
46480,0.537443,0.014717,0.000000,0.000000,0.000000,0.000000,0.000000,0.972732,2,0,...,0,0,0,0,0,0,0,1,0,0
47434,0.039711,0.110049,0.000542,0.000000,0.000442,0.000000,0.000000,0.999008,2,0,...,0,0,0,0,0,0,0,1,0,0
82142,0.174654,0.000879,0.000542,0.000000,0.000442,0.000565,0.000574,0.999504,1,0,...,0,0,0,0,0,0,0,0,0,1

In [116]:
X_test

,BLOCK,LOT,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,NEIGHBORHOOD_AIRPORT LA GUARDIA,...,11436,11691,11692,11693,11694,BOROUGH_1,BOROUGH_2,BOROUGH_3,BOROUGH_4,BOROUGH_5
70426,0.581015,0.005931,0.001085,0.000000,0.000885,0.000588,0.000471,0.987110,1,0,...,0,0,0,0,0,0,0,0,1,0
67066,0.166381,0.004833,0.000000,0.000442,0.000442,0.000594,0.000800,0.956867,4,0,...,0,0,0,0,0,0,0,0,1,0
72236,0.755607,0.010763,0.001085,0.000000,0.000885,0.000705,0.000400,0.951909,1,0,...,0,0,0,0,0,0,0,0,1,0
1989,0.051170,0.006919,0.000000,0.000000,0.000000,0.000000,0.000000,0.956867,2,0,...,0,0,0,0,0,1,0,0,0,0
29596,0.329636,0.142889,0.000542,0.000000,0.000442,0.000000,0.000000,0.999008,1,0,...,0,0,0,0,0,0,0,1,0,0
1727,0.066736,0.112685,0.000542,0.000000,0.000442,0.000000,0.000000,0.994051,2,0,...,0,0,0,0,0,1,0,0,0,0
15619,0.068268,0.203954,0.000542,0.000000,0.000442,0.000000,0.000000,0.981160,2,0,...,0,0,0,0,0,1,0,0,0,0
32987,0.025738,0.131906,0.000542,0.000000,0.000442,0.000000,0.000000,0.999008,1,0,...,0,0,0,0,0,0,0,1,0,0
82391,0.434122,0.000439,0.000542,0.000000,0.000442,0.000303,0.000339,0.987605,1,0,...,0,0,0,0,0,0,0,0,0,1
21334,0.160988,0.004503,0.001085,0.000000,0.000885,0.000388,0.000657,0.942489,1,0,...,0,0,0,0,0,0,1,0,0,0
44949,0.059689,0.000000,0.002711,0.000442,0.002654,0.000531,0.001030,0.957362,2,0,...,0,0,0,0,0,0,0,1,0,0
46986,0.045655,0.005382,0.001085,0.000000,0.000885,0.000471,0.000570,0.946951,1,0,...,0,0,0,0,0,0,0,1,0,0
47182,0.047310,0.005272,0.001627,0.000000,0.001327,0.000471,0.000723,0.942489,1,0,...,0,0,0,0,0,0,0,1,0,0
30336,0.534379,0.041076,0.000000,0.000000,0.000000,0.000000,0.000000,0.971244,2,0,...,0,0,0,0,0,0,0,1,0,0
14606,0.094252,0.132345,0.000542,0.000000,0.000442,0.000000,0.000000,0.984135,2,0,...,0,0,0,0,0,1,0,0,0,0
68472,0.551967,0.000549,0.001627,0.000000,0.001327,0.000470,0.000752,0.946951,1,0,...,0,0,0,0,0,0,0,0,1,0
72631,0.627467,0.000439,0.001085,0.000000,0.000885,0.000941,0.000336,0.956867,1,0,...,0,0,0,0,0,0,0,0,1,0
34408,0.073538,0.004174,0.004338,0.000000,0.003538,0.000611,0.002329,0.957362,2,0,...,0,0,0,0,0,0,0,1,0,0
15566,0.068146,0.152773,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,1,0,0,0,0
41765,0.416227,0.000110,0.000542,0.000000,0.000442,0.000523,0.000451,0.956867,1,0,...,0,0,0,0,0,0,0,1,0,0
58027,0.305001,0.166941,0.000542,0.000000,0.000442,0.000000,0.000000,0.998513,2,0,...,0,0,0,0,0,0,0,0,1,0
25190,0.285452,0.001098,0.002169,0.000000,0.001769,0.000560,0.000944,0.949430,2,0,...,0,0,0,0,0,0,1,0,0,0
21102,0.248989,0.001977,0.001085,0.000000,0.000885,0.000882,0.000570,0.954388,1,0,...,0,0,0,0,0,0,1,0,0,0
23156,0.364567,0.044481,0.000000,0.000000,0.000000,0.000000,0.000000,0.961329,2,0,...,0,0,0,0,0,0,1,0,0,0
23588,0.255423,0.002416,0.000000,0.001327,0.001327,0.000717,0.000755,0.957362,4,0,...,0,0,0,0,0,0,1,0,0,0
46494,0.538669,0.011312,0.000000,0.000000,0.000000,0.000000,0.000000,0.969261,2,0,...,0,0,0,0,0,0,0,1,0,0
71404,0.834968,0.000879,0.000542,0.000000,0.000442,0.001334,0.000341,0.969261,1,0,...,0,0,0,0,0,0,0,0,1,0
31168,0.219635,0.004833,0.001085,0.000000,0.000885,0.000470,0.000597,0.942489,1,0,...,0,0,0,0,0,0,0,1,0,0
16799,0.074458,0.001647,0.000000,0.000000,0.000000,0.000000,0.000000,0.941993,2,0,...,0,0,0,0,0,1,0,0,0,0
11184,0.000919,0.417133,0.000542,0.000000,0.000442,0.000000,0.000000,0.994546,2,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82792,0.208910,0.005272,0.000542,0.000000,0.000442,0.000382,0.000314,0.993555,1,0,...,0,0,0,0,0,0,0,0,0,1
34714,0.071884,0.110159,0.000542,0.000000,0.000442,0.000000,0.000000,0.000000,2,0,...,0,0,0,0,0,0,0,1,0,0
71723,0.735200,0.008677,0.000542,0.000000,0.000442,0.000477,0.000254,0.956867,1,0,...,1,0,0,0,0,0,0,0,1,0
39779,0.026474,0.006041,0.002169,0.000000,0.001769,0.000545,0.000837,0.951909,2,0,...,0,0,0,0,0,0,0,1,0,0
32069,0.210565,0.131796,0.000542,0.000000,0.000442,0.000000,0.000000,0.998513,2,0,...,0,0,0,0,0,0,0,1,0,0
54163,0.508825,0.007578,0.000542,0.000000,0.000442,0.000984,0.000317,0.966782,1,0,...,0,0,0,0,0,0,0,0,1,0
16905,0.075745,0.003075,0.000000,0.000000,0.000000,0.000000,0.000000,0.954388,2,0,...,0,0,0,0,0,1,0,0,0,0
46383,0.455448,0.004283,0.000000,0.000000,0.000000,0.000000,0.000000,0.971740,2,0,...,0,0,0,0,0,0,0,1,0,0
13883,0.092842,0.004503,0.000000,0.000000,0.000000,0.000000,0.000000,0.981656,2,0,...,0,0,0,0,0,1,0,0,0,0
74714,0.010786,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.957362,2,0,...,0,0,0,0,0,0,0,0,1,0
24328,0.340728,0.005052,0.001085,0.000000,0.000885,0.000588,0.000427,0.956867,1,0,...,0,0,0,0,0,0,1,0,0,0
14374,0.091371,0.111917,0.000542,0.000000,0.000442,0.000000,0.000000,0.985126,2,0,...,0,0,0,0,0,1,0,0,0,0
62399,0.642297,0.001538,0.000542,0.000000,0.000442,0.000564,0.000337,0.951909,1,0,...,0,0,0,0,0,0,0,0,1,0
20447,0.196960,0.004283,0.001085,0.000000,0.000885,0.001246,0.000933,0.942489,1,0,...,0,0,0,0,0,0,1,0,0,0
12215,0.086469,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.951909,2,0,...,0,0,0,0,0,1,0,0,0,0
18464,0.299363,0.005821,0.000542,0.000000,0.000442,0.000559,0.000187,0.956867,1,0,...,0,0,0,0,0,0,1,0,0,0
44658,0.059444,0.008567,0.000000,0.000000,0.000000,0.000000,0.000000,0.951909,2,0,...,0,0,0,0,0,0,0,1,0,0
82694,0.198309,0.000988,0.000542,0.000000,0.000442,0.000553,0.000288,0.971740,1,0,...,0,0,0,0,0,0,0,0,0,1
40181,0.434673,0.005052,0.001085,0.000000,0.000885,0.000417,0.000614,0.966782,1,0,...,0,0,0,0,0,0,0,1,0,0
33367,0.115946,0.121142,0.000542,0.000000,0.000442,0.000000,0.000000,0.995042,2,0,...,0,0,0,0,0,0,0,1,0,0
71215,0.994423,0.004393,0.000000,0.000000,0.000000,0.000000,0.000000,0.972236,2,0,...,0,0,0,0,1,0,0,0,1,0
52324,0.524513,0.001318,0.000542,0.000000,0.000442,0.000917,0.000335,0.961824,1,0,...,0,0,0,0,0,0,0,0,1,0
6450,0.057299,0.234377,0.000542,0.000000,0.000442,0.000000,0.000000,0.972732,2,0,...,0,0,0,0,0,1,0,0,0,0
5554,0.125260,0.132015,0.000000,0.000000,0.000000,0.000000,0.000000,0.994051,2,0,...,0,0,0,0,0,1,0,0,0,0
64340,0.089043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.969261,2,0,...,0,0,0,0,0,0,0,0,1,0
3839,0.035053,0.004613,0.000000,0.000000,0.000000,0.000000,0.000000,0.954883,2,0,...,0,0,0,0,0,1,0,0,0,0
64963,0.610430,0.003844,0.000542,0.000000,0.000442,0.001204,0.000476,0.964303,1,0,...,0,0,0,0,0,0,0,0,1,0
68262,0.554173,0.003515,0.001085,0.000000,0.000885,0.000470,0.000380,0.961824,1,0,...,0,0,0,0,0,0,0,0,1,0
6826,0.018997,0.001318,0.000000,0.000000,0.000000,0.000000,0.000000,0.971740,2,0,...,0,0,0,0,0,1,0,0,0,0
73073,0.721902,0.029544,0.000542,0.000000,0.000442,0.000439,0.000224,0.954388,1,0,...,0,0,0,0,0,0,0,0,1,0

### Applying the Random Forest Regressor Model.

In [106]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(max_depth=150, random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=150,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False)

In [107]:
y_p = regr.predict(X_test)

In [108]:
r_2  = regr.score(X_test, y_test)

In [109]:
print("The R2 Square: ",r_2)

The R2 Square:  0.1867099178002557

In [119]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_p))
print("Root Mean Squared Error: {}".format(rmse))

Root Mean Squared Error: 0.01107458996941554

In [111]:
y_p

array([0.00022667, 0.00022667, 0.00022667, ..., 0.00022667, 0.00040638,
       0.00022667])

In [112]:
y_test

array([0.00099693, 0.00133742, 0.00103528, ..., 0.00070245, 0.00075   ,
       0.00065184])